=== devonjones/PFSRD2-Data/monster_ability.schema.1.1.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",

	"definitions": {
		"action": {
			"type": "object",
			"properties": {
				"type": {"enum": ["stat_block_section"]},
				"subtype": {"enum": ["action"]},
				"name": {"enum": [
					"Reaction", "Free Action", "One Action",
					"Two Actions", "Three Actions", "One to Three Actions",
					"One or Two Actions", "Two or Three Actions"
				]}
			},
			"required": ["name", "type", "subtype"],
			"additionalProperties": false
		},
		"license": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["section"]},
				"subtype": {"enum": ["license"]},
				"license": {"enum": ["OPEN GAME LICENSE Version 1.0a"]},
				"text": {"type": "string"},
				"sections": {"$ref": "#/definitions/sections"}
			},
			"additionalProperties": false
		},
		"link": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["link"]},
				"alt": {"type": "string"},
				"href": {"type": "string"},
				"game-obj": {"enum": [
					"MonsterAbilities", "Sources", "Conditions", "Traits",
					"Rules", "Actions", "Skills", "Spells", "Rituals"
				]},
				"aonid": {"type": "integer"}
			},
			"required": ["name", "type", "alt"],
			"additionalProperties": false
		},
		"section": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["section"]},
				"text": {"type": "string"},
				"sections": {"$ref": "#/definitions/sections"},
				"sources": {"$ref": "#/definitions/sources"},
				"subtype": {"enum": ["sidebar", "index"]},
				"sidebar_type": {"enum": [
					"treasure_and_rewards", "related_creatures", "locations",
					"additional_lore", "advice_and_rules"
				]},
				"sidebar_heading": {"type": "string"},
				"image": {"$ref": "#/definitions/image"}
			},
			"additionalProperties": false
		},
		"sections": {
			"type": "array",
			"items": {"$ref": "#/definitions/section"},
			"additionalItems": false
		},
		"source": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["source"]},
				"link": {"$ref": "#/definitions/link"},
				"page": {"type": "integer"},
				"errata": {"$ref": "#/definitions/link"},
				"note": {"$ref": "#/definitions/link"}
			},
			"required": ["name", "type", "link"],
			"additionalProperties": false
		},
		"sources": {
			"type": "array",
			"items": {"$ref": "#/definitions/source"},
			"additionalItems": false
		},
		"abstract_trait": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["trait", "trait_template"]},
				"text": {"type": "string"}
			},
			"required": ["name", "type"],
			"dependencies": {
				"game-id": {"$ref": "#/definitions/trait"}
			}
		},
		"trait": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["trait"]},
				"game-id": {"type": "string"},
				"game-obj": {"enum": ["Traits"]},
				"value": {"type": "string"},
				"text": {"type": "string"},
				"classes": {
					"type": "array",
					"items": {"type": "string"},
					"additionalItems": false
				},
				"sources": {"$ref": "#/definitions/sources"},
				"links": {
					"type": "array",
					"items": {"$ref": "#/definitions/link"},
					"additionalItems": false
				}
			},
			"required": ["name", "type", "text", "game-id", "game-obj", "sources"],
			"additionalProperties": false
		},
		"traits": {
			"type": "array",
			"items": {"$ref": "#/definitions/abstract_trait"},
			"additionalItems": false
		},
		"trait_template": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["trait_template"]},
				"text": {"type": "string"}
			},
			"required": ["name", "type", "text"],
			"additionalProperties": false
		}
	},
	"type": "object",
	"properties": {
		"name": {"type": "string"},
		"type": {"enum": ["ability"]},
		"ability_type": {"enum": ["universal_monster_ability"]},
		"game-id": {"type": "string"},
		"game-obj": {"enum": ["MonsterAbilities"]},
		"aonid": {"type": "integer"},
		"value": {"type": "string"},
		"action": {"$ref": "#/definitions/action"},
		"text": {"type": "string"},
		"effect": {"type": "string"},
		"requirement": {"type": "string"},
		"trigger": {"type": "string"},
		"failure": {"type": "string"},
		"success": {"type": "string"},
		"critical_failure": {"type": "string"},
		"critical_success": {"type": "string"},
		"sources": {"$ref": "#/definitions/sources"},
		"traits": {"$ref": "#/definitions/traits"},
		"links": {
			"type": "array",
			"items": {"$ref": "#/definitions/link"},
			"additionalItems": false
		},
		"schema_version": {"enum": [1.1]},
		"license": {"$ref": "#/definitions/license"}
	},
	"required": ["name", "type", "game-id", "game-obj", "sources"],
	"additionalProperties": false
}

=== devonjones/PFSRD2-Data/monster_abilities/bestiary/at-will_spells.json
{
    "name": "At-Will Spells",
    "type": "ability",
    "text": "The monster can cast its at-will spells any number of times without using up spell slots.",
    "ability_type": "universal_monster_ability",
    "aonid": 4,
    "game-obj": "MonsterAbilities",
    "sources": [
        {
            "type": "source",
            "name": "Bestiary",
            "link": {
                "type": "link",
                "name": "Bestiary pg. 342",
                "alt": "Bestiary pg. 342",
                "game-obj": "Sources",
                "aonid": 2
            },
            "page": 342
        }
    ],
    "game-id": "6a105686111202ea0461d8516e246f37",
    "schema_version": 1.1
}

=== devonjones/PFSRD2-Data/monster_abilities/bestiary/knockdown.json
{
    "name": "Knockdown",
    "type": "ability",
    "text": "**Requirements** The monster\u2019s last action was a success with a Strike that lists Knockdown in its damage entry. **Effect** The monster knocks the target prone.",
    "ability_type": "universal_monster_ability",
    "aonid": 20,
    "game-obj": "MonsterAbilities",
    "action": {
        "type": "stat_block_section",
        "subtype": "action",
        "name": "One Action"
    },
    "sources": [
        {
            "type": "source",
            "name": "Bestiary",
            "link": {
                "type": "link",
                "name": "Bestiary pg. 343",
                "alt": "Bestiary pg. 343",
                "game-obj": "Sources",
                "aonid": 2
            },
            "page": 343
        }
    ],
    "requirement": "The monster\u2019s last action was a success with a Strike that lists Knockdown in its damage entry.",
    "effect": "The monster knocks the target prone.",
    "game-id": "0d950737e6e40c2cda6b2d9fe34b3270",
    "schema_version": 1.1
}
