=== devonjones/PFSRD2-Data/monster_family.schema.1.0.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"alternate_link": {
			"type": "object",
			"properties": {
				"type": {
					"enum": [
						"alternate_link"
					]
				},
				"game-obj": {
					"enum": [
						"Spells",
						"Sources",
						"Skills",
						"Traits",
						"MonsterAbilities",
						"Conditions",
						"Languages",
						"Weapons",
						"Armor",
						"Shields",
						"Equipment",
						"Deities",
						"Feats",
						"Actions",
						"Monsters",
						"Heritages",
						"Rules",
						"Diseases",
						"Rituals",
						"Planes",
						"MonsterFamilies",
						"Domains",
						"Classes",
						"Ancestries",
						"Archetypes",
						"SiegeWeapons",
						"WeaponGroups",
						"NPCs"
					]
				},
				"game-id": {
					"type": "string"
				},
				"alternate_type": {
					"enum": [
						"legacy",
						"remastered"
					]
				},
				"aonid": {
					"type": "integer"
				}
			},
			"required": [
				"game-obj",
				"aonid"
			],
			"additionalProperties": false
		},
		"link": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"type": {
					"enum": [
						"link"
					]
				},
				"alt": {
					"type": "string"
				},
				"href": {
					"type": "string"
				},
				"note": {
					"$ref": "#/definitions/link"
				},
				"game-obj": {
					"enum": [
						"Actions",
						"Ancestries",
						"AnimalCompanions",
						"Archetypes",
						"Armor",
						"Backgrounds",
						"Bloodlines",
						"Causes",
						"Classes",
						"Conditions",
						"Curses",
						"Deities",
						"DeityCategories",
						"Diseases",
						"Doctrines",
						"Domains",
						"DruidicOrders",
						"Equipment",
						"Familiars",
						"Feats",
						"Hazards",
						"Heritages",
						"HuntersEdge",
						"HybridStudies",
						"Innovations",
						"Instincts",
						"Languages",
						"MonsterAbilities",
						"MonsterFamilies",
						"MonsterTemplates",
						"Monsters",
						"Muses",
						"Mysteries",
						"NPCs",
						"Patrons",
						"Planes",
						"Rackets",
						"Relics",
						"ResearchFields",
						"Rituals",
						"Rules",
						"Shields",
						"Skills",
						"Sources",
						"Spells",
						"Traits",
						"WeaponGroups",
						"Weapons",
						"WeatherHazards"
					]
				},
				"aonid": {
					"type": "integer"
				}
			},
			"required": [
				"name",
				"type",
				"alt"
			],
			"additionalProperties": false
		},
		"license": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"type": {
					"enum": [
						"section"
					]
				},
				"subtype": {
					"enum": [
						"license"
					]
				},
				"license": {
					"enum": [
						"OPEN GAME LICENSE Version 1.0a",
						"Open RPG Creative license"
					]
				},
				"text": {
					"type": "string"
				},
				"sections": {
					"$ref": "#/definitions/sections"
				}
			},
			"additionalProperties": false
		},
		"section": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"type": {
					"enum": [
						"section"
					]
				},
				"text": {
					"type": "string"
				},
				"sections": {
					"$ref": "#/definitions/sections"
				},
				"sources": {
					"$ref": "#/definitions/sources"
				},
				"abilities": {
					"$ref": "#/definitions/abilities"
				},
				"subtype": {
					"enum": [
						"sidebar",
						"index"
					]
				},
				"sidebar_type": {
					"enum": [
						"treasure_and_rewards",
						"related_creatures",
						"locations",
						"additional_lore",
						"advice_and_rules",
						"geb"
					]
				},
				"sidebar_heading": {
					"type": "string"
				},
				"image": {
					"$ref": "#/definitions/image"
				},
				"action_type": {
					"$ref": "#/definitions/action_type"
				},
				"traits": {
					"$ref": "#/definitions/traits"
				},
				"links": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/link"
					},
					"additionalItems": false
				}
			},
			"additionalProperties": false
		},
		"sections": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/section"
			},
			"additionalItems": false
		},
		"source": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"type": {
					"enum": [
						"source"
					]
				},
				"link": {
					"$ref": "#/definitions/link"
				},
				"note": {
					"$ref": "#/definitions/link"
				},
				"page": {
					"type": "integer"
				},
				"errata": {
					"$ref": "#/definitions/link"
				}
			},
			"required": [
				"name",
				"type",
				"link",
				"page"
			],
			"additionalProperties": false
		},
		"sources": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/source"
			},
			"additionalItems": false
		},
		"action_type": {
			"type": "object",
			"properties": {
				"type": {
					"enum": [
						"stat_block_section"
					]
				},
				"subtype": {
					"enum": [
						"action_type"
					]
				},
				"name": {
					"enum": [
						"Reaction",
						"Free Action",
						"One Action",
						"Two Actions",
						"Three Actions",
						"One to Three Actions",
						"One or Two Actions",
						"Two or Three Actions",
						"Free Action or Single Action",
						"One or Three Actions",
						"One Action or more",
						"Two to Three Actions",
						"Reaction or One Action"
					]
				}
			},
			"required": [
				"name",
				"type",
				"subtype"
			],
			"additionalProperties": false
		},
		"effect": {
			"type": "object",
			"properties": {
				"target": {
					"type": "string"
				},
				"operation": {
					"enum": [
						"adjustment",
						"add_item",
						"add_items",
						"add_modifier",
						"no_op",
						"replace",
						"remove_item",
						"replace_highest_with",
						"replace_one_die",
						"select",
						"set_reach",
						"size_increment"
					]
				},
				"value": {},
				"value_from": {
					"type": "string"
				},
				"conditional": {
					"type": "string"
				},
				"item": {
					"type": "object"
				},
				"modifier": {
					"type": "object"
				},
				"name": {
					"type": "string"
				},
				"movement_type": {
					"type": "string"
				},
				"minimum": {
					"type": "integer"
				},
				"selection": {
					"type": "object"
				},
				"source": {
					"type": "string"
				}
			},
			"required": [
				"target",
				"operation"
			],
			"additionalProperties": false
		},
		"change": {
			"type": "object",
			"properties": {
				"type": {
					"enum": [
						"stat_block_section"
					]
				},
				"subtype": {
					"enum": [
						"change"
					]
				},
				"text": {
					"type": "string"
				},
				"change_category": {
					"enum": [
						"abilities",
						"attributes",
						"combat_stats",
						"damage",
						"gear",
						"hit_points",
						"immunities",
						"languages",
						"level",
						"resistances",
						"senses",
						"size",
						"skills",
						"speed",
						"spells",
						"strikes",
						"traits",
						"weaknesses",
						"unknown"
					]
				},
				"effects": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/effect"
					},
					"additionalItems": false
				},
				"links": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/link"
					},
					"additionalItems": false
				}
			},
			"required": [
				"type",
				"subtype",
				"text",
				"change_category"
			],
			"additionalProperties": false
		},
		"ability": {
			"type": "object",
			"properties": {
				"type": {
					"enum": [
						"stat_block_section"
					]
				},
				"subtype": {
					"enum": [
						"ability"
					]
				},
				"name": {
					"type": "string"
				},
				"text": {
					"type": "string"
				},
				"action_type": {
					"$ref": "#/definitions/action_type"
				},
				"link": {
					"$ref": "#/definitions/link"
				},
				"links": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/link"
					},
					"additionalItems": false
				}
			},
			"required": [
				"name",
				"type",
				"subtype"
			],
			"additionalProperties": false
		},
		"monster_family_section": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"type": {
					"enum": [
						"section",
						"stat_block_section"
					]
				},
				"subtype": {
					"enum": [
						"monster_family"
					]
				},
				"text": {
					"type": "string"
				},
				"sources": {
					"$ref": "#/definitions/sources"
				},
				"links": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/link"
					},
					"additionalItems": false
				},
				"abilities": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ability"
					},
					"additionalItems": false
				},
				"changes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/change"
					},
					"additionalItems": false
				},
				"sections": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/monster_family_section"
					},
					"additionalItems": false
				}
			},
			"additionalProperties": false
		}
	},
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"type": {
			"enum": [
				"monster_family"
			]
		},
		"aonid": {
			"type": "integer"
		},
		"game-obj": {
			"enum": [
				"MonsterFamilies"
			]
		},
		"game-id": {
			"type": "string"
		},
		"sources": {
			"$ref": "#/definitions/sources"
		},
		"text": {
			"type": "string"
		},
		"sections": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/monster_family_section"
			},
			"additionalItems": false
		},
		"links": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/link"
			},
			"additionalItems": false
		},
		"alternate_link": {
			"$ref": "#/definitions/alternate_link"
		},
		"edition": {
			"enum": [
				"legacy",
				"remastered"
			]
		},
		"schema_version": {
			"enum": [
				1.0
			]
		},
		"license": {
			"$ref": "#/definitions/license"
		}
	},
	"required": [
		"name",
		"type",
		"aonid",
		"game-obj",
		"sources",
		"license",
		"schema_version"
	],
	"additionalProperties": false
}

=== devonjones/PFSRD2-Data/monsterfamilies/monster_core/crawling_hand.json
{
    "name": "Crawling hand",
    "type": "monster_family",
    "sections": [
        {
            "name": "Crawling hand",
            "type": "stat_block_section",
            "subtype": "monster_family"
        },
        {
            "name": "Crawling Hand Origins",
            "type": "section",
            "text": "A popular tale among necromancers tells of an ancient wizard who trafficked in evil magic. During a summoning ritual gone wrong, the wizard's hand became possessed and later strangled them while they slept. The hand dragged the corpse across the wizard's rooms to their workbench, propped up a knife in a vise, and severed itself from the rest of the body. According to the story, the hand went on to commit several more murders and disappeared into the sewers of a major metropolis, never to be seen again. Some necromancers believe that this original crawling hand still creeps through the shadows of that city, killing as it pleases.",
            "sources": [
                {
                    "type": "source",
                    "name": "Monster Core",
                    "link": {
                        "type": "link",
                        "name": "Monster Core pg. 68",
                        "alt": "Monster Core pg. 68",
                        "game-obj": "Sources",
                        "aonid": 221
                    },
                    "page": 68,
                    "errata": {
                        "type": "link",
                        "name": "1.1",
                        "alt": "1.1",
                        "game-obj": "Sources",
                        "aonid": 221
                    }
                }
            ]
        }
    ],
    "alternate_link": {
        "type": "alternate_link",
        "game-obj": "MonsterFamilies",
        "aonid": 130,
        "alternate_type": "legacy"
    },
    "sources": [
        {
            "type": "source",
            "name": "Monster Core",
            "link": {
                "type": "link",
                "name": "Monster Core pg. 68",
                "alt": "Monster Core pg. 68",
                "game-obj": "Sources",
                "aonid": 221
            },
            "page": 68,
            "errata": {
                "type": "link",
                "name": "1.1",
                "alt": "1.1",
                "game-obj": "Sources",
                "aonid": 221
            }
        }
    ],
    "aonid": 383,
    "game-obj": "MonsterFamilies",
    "game-id": "b7f6e0ec39403d30fa9e30f00a2343d9",
    "text": "Typically, crawling hands form when severed appendages are endowed with a crude sentience by necromantic energies that turn them into tireless killers. Yet, crawling hands can also arise spontaneously, usually when a creature loses an appendage in a place rife with necromantic energy or with a connection to the Void.",
    "links": [
        {
            "type": "link",
            "name": "the Void",
            "alt": "the Void",
            "game-obj": "Planes",
            "aonid": 28
        }
    ],
    "edition": "remastered",
    "license": {
        "name": "ORC Notice",
        "type": "section",
        "sections": [
            {
                "name": "Attribution",
                "type": "section",
                "text": "This product is based on the following Licensed Material:",
                "sections": [
                    {
                        "name": "Monster Core",
                        "type": "section",
                        "text": "***Pathfinder Monster Core*** \u00a9 2024 Paizo Inc., Authors: Alexander Augunas, Dennis Baker, Kate Baker, Joshua Birdsong, Joseph Blomquist, Logan Bonner, Jason Bulmahn, James Case, John Compton, Paris Crenshaw, Adam Daigle, Darrin Drader, Brian Duckwitz, Robert N. Emerson, Scott Fernandez, Eleanor Ferron, Leo Glass, Matthew Goodall, BJ Hensley, Thurston Hillman, Vanessa Hoskins, James Jacobs, Jenny Jarzabski, Miko Kallio, Jason Keeley, Jeff Lee, Lyz Liddell, Luis Loza, Ron Lundeen, Robert G. McCreary, Philippe-Antoine Menard, Jacob W. Michaels, Dave Nelson, Jason Nelson, Tim Nightengale, Stephen Radney-MacFarland, Mikhail Rekun, Patrick Renie, Alex Riggs, David N. Ross, Michael Sayre, Mark Seifter, Chris S. Sims, Amber Stewart, Jeffrey Swank, William Thompson, Jason Tondro, Clark Valentine, Landon Winkler, Tonya Woldridge, and Linda Zayas-Palmer"
                    }
                ]
            },
            {
                "name": "Attributing us",
                "type": "section",
                "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
                "sections": [
                    {
                        "name": "Pathfinder Open Reference",
                        "type": "section",
                        "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones."
                    }
                ]
            },
            {
                "name": "Reserved Material",
                "type": "section",
                "text": "Reserved Material elements in this product include, but may not be limited to: [none]"
            },
            {
                "name": "Expressly Designated Licensed Material",
                "type": "section",
                "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None]."
            }
        ],
        "subtype": "license",
        "license": "Open RPG Creative license",
        "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein."
    },
    "schema_version": 1.0
}
