=== devonjones/PFSRD2-Data/trait.schema.1.1.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",

	"definitions": {
		"alternate_link": {
			"type": "object",
			"properties": {
				"type": {"enum": ["alternate_link"]},
				"game-obj": {"enum": [
					"Spells", "Sources", "Skills", "Traits", "MonsterAbilities",
					"Conditions", "Languages", "Weapons", "Armor", "Shields",
					"Equipment", "Deities", "Feats", "Actions", "Monsters",
					"Heritages", "Rules", "Diseases", "Rituals", "Planes",
					"MonsterFamilies", "Domains", "Classes", "Ancestries",
					"Archetypes", "SiegeWeapons", "WeaponGroups"
				]},
				"game-id": {"type": "string"},
				"alternate_type": {"enum": ["legacy", "remastered"]},
				"aonid": {"type": "integer"}
			},
			"required": ["game-obj", "aonid"],
			"additionalProperties": false
		},
		"license": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["section"]},
				"subtype": {"enum": ["license"]},
				"license": {"enum": [
					"OPEN GAME LICENSE Version 1.0a",
					"Open RPG Creative license"]},
				"text": {"type": "string"},
				"sections": {"$ref": "#/definitions/sections"}
			},
			"additionalProperties": false
		},
		"link": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["link"]},
				"alt": {"type": "string"},
				"href": {"type": "string"},
				"game-obj": {"enum": [
					"Spells", "Sources", "Skills", "Traits", "MonsterAbilities",
					"Conditions", "Languages", "Weapons", "Armor", "Shields",
					"Equipment", "Deities", "Feats", "Actions", "Monsters",
					"Heritages", "Rules", "Diseases", "Rituals", "Planes",
					"MonsterFamilies", "Domains", "Classes", "Ancestries",
					"Archetypes", "SiegeWeapons", "WeaponGroups"
				]},
				"aonid": {"type": "integer"}
			},
			"required": ["name", "type", "alt"],
			"additionalProperties": false
		},
		"section": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["section"]},
				"text": {"type": "string"},
				"sections": {"$ref": "#/definitions/sections"},
				"sources": {"$ref": "#/definitions/sources"},
				"subtype": {"enum": ["sidebar", "index"]},
				"sidebar_type": {"enum": [
					"treasure_and_rewards", "related_creatures", "locations",
					"additional_lore", "advice_and_rules"
				]},
				"sidebar_heading": {"type": "string"},
				"image": {"$ref": "#/definitions/image"}
			},
			"additionalProperties": false
		},
		"sections": {
			"type": "array",
			"items": {"$ref": "#/definitions/section"},
			"additionalItems": false
		},
		"source": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["source"]},
				"link": {"$ref": "#/definitions/link"},
				"page": {"type": "integer"},
				"errata": {"$ref": "#/definitions/link"},
				"note": {"$ref": "#/definitions/link"}
			},
			"required": ["name", "type", "link"],
			"additionalProperties": false
		},
		"sources": {
			"type": "array",
			"items": {"$ref": "#/definitions/source"},
			"additionalItems": false
		}
	},
	"type": "object",
	"properties": {
		"name": {"type": "string"},
		"type": {"enum": ["trait"]},
		"game-id": {"type": "string"},
		"game-obj": {"enum": ["Traits"]},
		"aonid": {"type": "integer"},
		"value": {"type": "string"},
		"text": {"type": "string"},
		"classes": {
			"type": "array",
			"items": {"type": "string"},
			"additionalItems": false
		},
		"sources": {"$ref": "#/definitions/sources"},
		"sections": {"$ref": "#/definitions/sections"},
		"links": {
			"type": "array",
			"items": {"$ref": "#/definitions/link"},
			"additionalItems": false
		},
		"alternate_link": {"$ref": "#/definitions/alternate_link"},
		"schema_version": {"enum": [1.1]},
		"edition": {"enum": ["legacy", "remastered"]},
		"license": {"$ref": "#/definitions/license"}
	},
	"required": ["name", "type", "game-id", "game-obj", "sources", "license", "schema_version", "edition"],
	"additionalProperties": false
}

=== devonjones/PFSRD2-Data/traits/treasure_vault_remastered/hefty.json
{
    "name": "Hefty",
    "type": "trait",
    "edition": "remastered",
    "sources": [
        {
            "type": "source",
            "name": "Treasure Vault (Remastered)",
            "link": {
                "type": "link",
                "name": "Treasure Vault (Remastered)",
                "alt": "Treasure Vault (Remastered)",
                "game-obj": "Sources",
                "aonid": 191
            },
            "page": 219,
            "errata": {
                "type": "link",
                "name": "2.0",
                "alt": "2.0",
                "game-obj": "Sources",
                "aonid": 191
            }
        }
    ],
    "aonid": 478,
    "game-obj": "Traits",
    "game-id": "790b3f0b98782431fda8f0bcc0625141",
    "text": "A hefty shield is so heavy that raising it takes more effort. Raising a Shield with the hefty trait is a two-action activity unless your Strength modifier equals or exceeds the number with the trait.",
    "links": [
        {
            "type": "link",
            "name": "Raising a Shield",
            "alt": "Raising a Shield",
            "game-obj": "Actions",
            "aonid": 98
        }
    ],
    "license": {
        "name": "ORC Notice",
        "type": "section",
        "sections": [
            {
                "name": "Attribution",
                "type": "section",
                "text": "This product is based on the following Licensed Material:",
                "sections": [
                    {
                        "name": "Treasure Vault",
                        "type": "section",
                        "text": "***Pathfinder Core Rulebook (Second Edition)*** \u00a9 2019, Paizo Inc.; Authors: Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter.  \n ***Pathfinder Treasure Vault*** \u00a9 2023, Paizo Inc.; Authors: Michael Sayre, Mark Seifter, Kendra Leigh Speedling, Logan Bonner, Dan Cascone, Jessica Catalan, Kim Frandsen, Andrew Geels, Steven Hammond, Sen H.H.S., Joshua Kim, Dustin Knight, Luis Loza, Jacob W. Michaels, Matt Morris, Dave Nelson, Stephen Radney-McFarland, Jessica Redekop, Andrew Stoeckle, Mari Tokuda, and Andrew White."
                    }
                ]
            },
            {
                "name": "Attributing us",
                "type": "section",
                "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
                "sections": [
                    {
                        "name": "Pathfinder Open Reference",
                        "type": "section",
                        "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones."
                    }
                ]
            },
            {
                "name": "Reserved Material",
                "type": "section",
                "text": "Reserved Material elements in this product include, but may not be limited to: [none]"
            },
            {
                "name": "Expressly Designated Licensed Material",
                "type": "section",
                "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None]."
            }
        ],
        "subtype": "license",
        "license": "Open RPG Creative license",
        "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein."
    },
    "schema_version": 1.1
}

=== devonjones/PFSRD2-Data/traits/treasure_vault/barding.json
{
    "name": "Barding",
    "type": "trait",
    "edition": "remastered",
    "sources": [
        {
            "type": "source",
            "name": "Treasure Vault",
            "link": {
                "type": "link",
                "name": "Treasure Vault pg. 216",
                "alt": "Treasure Vault pg. 216",
                "game-obj": "Sources",
                "aonid": 191
            },
            "page": 216,
            "errata": {
                "type": "link",
                "name": "2.0",
                "alt": "2.0",
                "game-obj": "Sources",
                "aonid": 191
            }
        }
    ],
    "aonid": 470,
    "game-obj": "Traits",
    "game-id": "2966f11f4be7a7d43c95dcd993226ac6",
    "text": "You can purchase special armor for animals, called barding. All animals have a trained proficiency rank in light barding, and combat-trained animals are trained in heavy barding. Barding uses the same rules as armor except for the following. The Price and Bulk of barding depend on the animal's size. Unlike for a suit of armor, barding's Strength entry is listed as a modifier, not a score. Barding can't be etched with magic runes, though special magical barding might be available.",
    "links": [
        {
            "type": "link",
            "name": "runes",
            "alt": "runes",
            "href": "Equipment.aspx?Category=23"
        }
    ],
    "license": {
        "name": "ORC Notice",
        "type": "section",
        "sections": [
            {
                "name": "Attribution",
                "type": "section",
                "text": "This product is based on the following Licensed Material:",
                "sections": [
                    {
                        "name": "Treasure Vault",
                        "type": "section",
                        "text": "***Pathfinder Core Rulebook (Second Edition)*** \u00a9 2019, Paizo Inc.; Authors: Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter.  \n ***Pathfinder Treasure Vault*** \u00a9 2023, Paizo Inc.; Authors: Michael Sayre, Mark Seifter, Kendra Leigh Speedling, Logan Bonner, Dan Cascone, Jessica Catalan, Kim Frandsen, Andrew Geels, Steven Hammond, Sen H.H.S., Joshua Kim, Dustin Knight, Luis Loza, Jacob W. Michaels, Matt Morris, Dave Nelson, Stephen Radney-McFarland, Jessica Redekop, Andrew Stoeckle, Mari Tokuda, and Andrew White."
                    }
                ]
            },
            {
                "name": "Attributing us",
                "type": "section",
                "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
                "sections": [
                    {
                        "name": "Pathfinder Open Reference",
                        "type": "section",
                        "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones."
                    }
                ]
            },
            {
                "name": "Reserved Material",
                "type": "section",
                "text": "Reserved Material elements in this product include, but may not be limited to: [none]"
            },
            {
                "name": "Expressly Designated Licensed Material",
                "type": "section",
                "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None]."
            }
        ],
        "subtype": "license",
        "license": "Open RPG Creative license",
        "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein."
    },
    "schema_version": 1.1
}

=== devonjones/PFSRD2-Data/traits/monster_core_2/munavri.json
{
    "name": "Munavri",
    "type": "trait",
    "alternate_link": {
        "type": "alternate_link",
        "game-obj": "Traits",
        "aonid": 358,
        "alternate_type": "legacy"
    },
    "edition": "remastered",
    "sources": [
        {
            "type": "source",
            "name": "Monster Core 2",
            "link": {
                "type": "link",
                "name": "Monster Core 2 pg. 365",
                "alt": "Monster Core 2 pg. 365",
                "game-obj": "Sources",
                "aonid": 276
            },
            "page": 365
        }
    ],
    "aonid": 880,
    "game-obj": "Traits",
    "game-id": "5cc41797f19d94efc9f71f9ff4c38c68",
    "text": "Amicable humanoids living in the Darklands, munavris have powerful telekinetic and psychic abilities.",
    "license": {
        "name": "ORC Notice",
        "type": "section",
        "sections": [
            {
                "name": "Attribution",
                "type": "section",
                "text": "This product is based on the following Licensed Material:",
                "sections": [
                    {
                        "name": "Monster Core 2",
                        "type": "section",
                        "text": "***Pathfinder Monster Core 2*** \u00a9 2025 Paizo Inc., Authors: Alexander Augunas, Jesse Benner, Joshua Birdsong, Logan Bonner, Jason Bulmahn, James Case, Jessica Catalan, John Compton, Paris Crenshaw, Adam Daigle, Katina Davis, Jesse Decker, Darrin Drader, Felix Dritz, Brian Duckwitz, Robert N. Emerson, Scott Fernandez, Eleanor Ferron, Hexe Fey, Benjamin U. Fields, Keith Garret, Scott Gladstein, Leo Glass, Matthew Goodall, Alice Grizzle, T.H. Gulliver, Sen H.H.S., Steven Hammond, Tim Hitchcock, Joan Hong, Vanessa Hoskins, James Jacobs, Brian R. James, Michelle Jones, TJ Kahn, Mikko Kallio, Jason Keeley, Joshua Kim, Avi Kool, John Laffan, Lyz Liddell, Luis Loza, Colm Lundberg, Ron Lundeen, Mahpiya, Philippe-Antoine Menard, Jacob W. Michaels, Patchen Mortimer, Dennis Muldoon, Andrew Mullen, Quinn Murphy, Dave Nelson, Jason Nelson, K. Tessa Newton, Tim Nightengale, Samantha Phelan, Randy Price, Stephen Radney-MacFarland, BJ Recio, Jessica Redekop, Mikhail Rekun, Patrick Renie, Alex Riggs, David N. Ross, Simone D. Sall\u00e9, Michael Sayre, David Schwartz, Mark Seifter, Chris S. Sims, Rodney Sloan, Shay Snow, Kendra Leigh Speedling, Amber Stewart, Jeffrey Swank, Tan Shao Han, Russ Taylor, William Thompson, Jason Tondro, Clark Valentine, Ruvaid Virk, Andrew White, Landon Winkler, and Linda Zayas-Palmer"
                    }
                ]
            },
            {
                "name": "Attributing us",
                "type": "section",
                "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
                "sections": [
                    {
                        "name": "Pathfinder Open Reference",
                        "type": "section",
                        "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones."
                    }
                ]
            },
            {
                "name": "Reserved Material",
                "type": "section",
                "text": "Reserved Material elements in this product include, but may not be limited to: [none]"
            },
            {
                "name": "Expressly Designated Licensed Material",
                "type": "section",
                "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None]."
            }
        ],
        "subtype": "license",
        "license": "Open RPG Creative license",
        "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein."
    },
    "schema_version": 1.1
}

=== devonjones/PFSRD2-Data/traits/player_core/incapacitation.json
{
  "alternate_link": {
    "alternate_type": "legacy",
    "aonid": 93,
    "game-obj": "Traits",
    "type": "alternate_link"
  },
  "aonid": 631,
  "edition": "remastered",
  "game-id": "b26076555c07646f046dd58e7d5b3885",
  "game-obj": "Traits",
  "license": {
    "license": "Open RPG Creative license",
    "name": "ORC Notice",
    "sections": [
      {
        "name": "Attribution",
        "sections": [
          {
            "name": "Player Core",
            "text": "***Pathfinder Player Core*** \u00a9 2023 Paizo Inc., Designed by Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter. Authors: Alexander Augunas, Kate Baker, Logan Bonner, Jason Bulmahn, Carlos Cabrera, Calder CaDavid, James Case, Eleanor Ferron, Steven Hammond, Joan Hong, Vanessa Hoskins, James Jacobs, Jenny Jarzabski, Erik Keith, Dustin Knight, Lyz Liddell, Luis Loza, Patchen Mortimer, Dennis Muldoon, Stephen Radney-MacFarland, Mikhail Rekun, David N. Ross, Michael Sayre, Mark Seifter, Kendra Leigh Speedling, Mark Thompson, Clark Valentine, Andrew White, Landon Winkler, and Linda Zayas-Palmer",
            "type": "section"
          }
        ],
        "text": "This product is based on the following Licensed Material:",
        "type": "section"
      },
      {
        "name": "Attributing us",
        "sections": [
          {
            "name": "Pathfinder Open Reference",
            "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones.",
            "type": "section"
          }
        ],
        "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
        "type": "section"
      },
      {
        "name": "Reserved Material",
        "text": "Reserved Material elements in this product include, but may not be limited to: [none]",
        "type": "section"
      },
      {
        "name": "Expressly Designated Licensed Material",
        "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None].",
        "type": "section"
      }
    ],
    "subtype": "license",
    "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein.",
    "type": "section"
  },
  "name": "Incapacitation",
  "schema_version": 1.1,
  "sources": [
    {
      "errata": {
        "alt": "2.0",
        "aonid": 216,
        "game-obj": "Sources",
        "name": "2.0",
        "type": "link"
      },
      "link": {
        "alt": "Player Core pg. 457",
        "aonid": 216,
        "game-obj": "Sources",
        "name": "Player Core pg. 457",
        "type": "link"
      },
      "name": "Player Core",
      "page": 457,
      "type": "source"
    }
  ],
  "text": "An ability with this trait can take a character completely out of the fight or even kill them, and it\u2019s harder to use on a more powerful character. If a spell has the incapacitation trait, any creature of more than twice the spell\u2019s rank treats the result of their check to prevent being incapacitated by the spell as one degree of success better, or the result of any check the spellcaster made to incapacitate them as one degree of success worse. If any other effect has the incapacitation trait, a creature of higher level than the item, creature, or hazard generating the effect gains the same benefits.",
  "type": "trait"
}
