=== devonjones/PFSRD2-Data/trait.schema.1.1.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",

	"definitions": {
		"alternate_link": {
			"type": "object",
			"properties": {
				"type": {"enum": ["alternate_link"]},
				"game-obj": {"enum": [
					"Spells", "Sources", "Skills", "Traits", "MonsterAbilities",
					"Conditions", "Languages", "Weapons", "Armor", "Shields",
					"Equipment", "Deities", "Feats", "Actions", "Monsters",
					"Heritages", "Rules", "Diseases", "Rituals", "Planes",
					"MonsterFamilies", "Domains", "Classes", "Ancestries",
					"Archetypes", "SiegeWeapons", "WeaponGroups"
				]},
				"game-id": {"type": "string"},
				"alternate_type": {"enum": ["legacy", "remastered"]},
				"aonid": {"type": "integer"}
			},
			"required": ["game-obj", "aonid"],
			"additionalProperties": false
		},
		"license": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["section"]},
				"subtype": {"enum": ["license"]},
				"license": {"enum": [
					"OPEN GAME LICENSE Version 1.0a",
					"Open RPG Creative license"]},
				"text": {"type": "string"},
				"sections": {"$ref": "#/definitions/sections"}
			},
			"additionalProperties": false
		},
		"link": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["link"]},
				"alt": {"type": "string"},
				"href": {"type": "string"},
				"game-obj": {"enum": [
					"Spells", "Sources", "Skills", "Traits", "MonsterAbilities",
					"Conditions", "Languages", "Weapons", "Armor", "Shields",
					"Equipment", "Deities", "Feats", "Actions", "Monsters",
					"Heritages", "Rules", "Diseases", "Rituals", "Planes",
					"MonsterFamilies", "Domains", "Classes", "Ancestries",
					"Archetypes", "SiegeWeapons", "WeaponGroups"
				]},
				"aonid": {"type": "integer"}
			},
			"required": ["name", "type", "alt"],
			"additionalProperties": false
		},
		"section": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["section"]},
				"text": {"type": "string"},
				"sections": {"$ref": "#/definitions/sections"},
				"sources": {"$ref": "#/definitions/sources"},
				"subtype": {"enum": ["sidebar", "index"]},
				"sidebar_type": {"enum": [
					"treasure_and_rewards", "related_creatures", "locations",
					"additional_lore", "advice_and_rules"
				]},
				"sidebar_heading": {"type": "string"},
				"image": {"$ref": "#/definitions/image"}
			},
			"additionalProperties": false
		},
		"sections": {
			"type": "array",
			"items": {"$ref": "#/definitions/section"},
			"additionalItems": false
		},
		"source": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"type": {"enum": ["source"]},
				"link": {"$ref": "#/definitions/link"},
				"page": {"type": "integer"},
				"errata": {"$ref": "#/definitions/link"},
				"note": {"$ref": "#/definitions/link"}
			},
			"required": ["name", "type", "link"],
			"additionalProperties": false
		},
		"sources": {
			"type": "array",
			"items": {"$ref": "#/definitions/source"},
			"additionalItems": false
		}
	},
	"type": "object",
	"properties": {
		"name": {"type": "string"},
		"type": {"enum": ["trait"]},
		"game-id": {"type": "string"},
		"game-obj": {"enum": ["Traits"]},
		"aonid": {"type": "integer"},
		"value": {"type": "string"},
		"text": {"type": "string"},
		"classes": {
			"type": "array",
			"items": {"type": "string"},
			"additionalItems": false
		},
		"sources": {"$ref": "#/definitions/sources"},
		"sections": {"$ref": "#/definitions/sections"},
		"links": {
			"type": "array",
			"items": {"$ref": "#/definitions/link"},
			"additionalItems": false
		},
		"alternate_link": {"$ref": "#/definitions/alternate_link"},
		"schema_version": {"enum": [1.1]},
		"edition": {"enum": ["legacy", "remastered"]},
		"license": {"$ref": "#/definitions/license"}
	},
	"required": ["name", "type", "game-id", "game-obj", "sources", "license", "schema_version", "edition"],
	"additionalProperties": false
}

=== devonjones/PFSRD2-Data/traits/player_core/aberration.json
{
  "alternate_link": {
    "alternate_type": "legacy",
    "aonid": 1,
    "game-obj": "Traits",
    "type": "alternate_link"
  },
  "aonid": 523,
  "edition": "remastered",
  "game-id": "00eec53f8ff824a5080c3d092eecd593",
  "game-obj": "Traits",
  "license": {
    "license": "Open RPG Creative license",
    "name": "ORC Notice",
    "sections": [
      {
        "name": "Attribution",
        "sections": [
          {
            "name": "Player Core",
            "text": "***Pathfinder Player Core*** \u00a9 2023 Paizo Inc., Designed by Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter. Authors: Alexander Augunas, Kate Baker, Logan Bonner, Jason Bulmahn, Carlos Cabrera, Calder CaDavid, James Case, Eleanor Ferron, Steven Hammond, Joan Hong, Vanessa Hoskins, James Jacobs, Jenny Jarzabski, Erik Keith, Dustin Knight, Lyz Liddell, Luis Loza, Patchen Mortimer, Dennis Muldoon, Stephen Radney-MacFarland, Mikhail Rekun, David N. Ross, Michael Sayre, Mark Seifter, Kendra Leigh Speedling, Mark Thompson, Clark Valentine, Andrew White, Landon Winkler, and Linda Zayas-Palmer",
            "type": "section"
          }
        ],
        "text": "This product is based on the following Licensed Material:",
        "type": "section"
      },
      {
        "name": "Attributing us",
        "sections": [
          {
            "name": "Pathfinder Open Reference",
            "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones.",
            "type": "section"
          }
        ],
        "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
        "type": "section"
      },
      {
        "name": "Reserved Material",
        "text": "Reserved Material elements in this product include, but may not be limited to: [none]",
        "type": "section"
      },
      {
        "name": "Expressly Designated Licensed Material",
        "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None].",
        "type": "section"
      }
    ],
    "subtype": "license",
    "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein.",
    "type": "section"
  },
  "name": "Aberration",
  "schema_version": 1.1,
  "sources": [
    {
      "errata": {
        "alt": "2.0",
        "aonid": 216,
        "game-obj": "Sources",
        "name": "2.0",
        "type": "link"
      },
      "link": {
        "alt": "Player Core pg. 452",
        "aonid": 216,
        "game-obj": "Sources",
        "name": "Player Core pg. 452",
        "type": "link"
      },
      "name": "Player Core",
      "page": 452,
      "type": "source"
    }
  ],
  "text": "Aberrations are creatures from beyond the planes or corruptions of the natural order.",
  "type": "trait"
}

=== devonjones/PFSRD2-Data/traits/core_rulebook/goblin.json
{
  "alternate_link": {
    "alternate_type": "remastered",
    "aonid": 618,
    "game-obj": "Traits",
    "type": "alternate_link"
  },
  "aonid": 81,
  "edition": "legacy",
  "game-id": "71ec3508832377630069abf128ad1a81",
  "game-obj": "Traits",
  "license": {
    "license": "OPEN GAME LICENSE Version 1.0a",
    "name": "OPEN GAME LICENSE Version 1.0a",
    "sections": [
      {
        "name": "Core Rulebook",
        "text": "**Pathfinder Core Rulebook (Second Edition)** \u00a9 2019, Paizo Inc.; Designers: Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter.",
        "type": "section"
      }
    ],
    "subtype": "license",
    "text": "The following text is the property of Wizards of the Coast, Inc. and is Copyright 2000 Wizards of the Coast, Inc (\"Wizards\"). All Rights Reserved. **1. Definitions**: (a)\"Contributors\" means the copyright and/or trademark owners who have contributed Open Game Content; (b)\"Derivative Material\" means copyrighted material including derivative works and translations (including into other computer languages), potation, modification, correction, addition, extension, upgrade, improvement, compilation, abridgment or other form in which an existing work may be recast, transformed or adapted; (c) \"Distribute\" means to reproduce, license, rent, lease, sell, broadcast, publicly display, transmit or otherwise distribute; (d)\"Open Game Content\" means the game mechanic and includes the methods, procedures, processes and routines to the extent such content does not embody the Product Identity and is an enhancement over the prior art and any additional content clearly identified as Open Game Content by the Contributor, and means any work covered by this License, including translations and derivative works under copyright law, but specifically excludes Product Identity. (e) \"Product Identity\" means product and product line names, logos and identifying marks including trade dress; artifacts; creatures characters; stories, storylines, plots, thematic elements, dialogue, incidents, language, artwork, symbols, designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual or audio representations; names and descriptions of characters, spells, enchantments, personalities, teams, personas, likenesses and special abilities; places, locations, environments, creatures, equipment, magical or supernatural abilities or effects, logos, symbols, or graphic designs; and any other trademark or registered trademark clearly identified as Product identity by the owner of the Product Identity, and which specifically excludes the Open Game Content; (f) \"Trademark\" means the logos, names, mark, sign, motto, designs that are used by a Contributor to identify itself or its products or the associated products contributed to the Open Game License by the Contributor (g) \"Use\", \"Used\" or \"Using\" means to use, Distribute, copy, edit, format, modify, translate and otherwise create Derivative Material of Open Game Content. (h) \"You\" or \"Your\" means the licensee in terms of this agreement. **2. The License**: This License applies to any Open Game Content that contains a notice indicating that the Open Game Content may only be Used under and in terms of this License. You must affix such a notice to any Open Game Content that you Use. No terms may be added to or subtracted from this License except as described by the License itself. No other terms or conditions may be applied to any Open Game Content distributed using this License. **3. Offer and Acceptance**: By Using the Open Game Content You indicate Your acceptance of the terms of this License. **4. Grant and Consideration**: In consideration for agreeing to use this License, the Contributors grant You a perpetual, worldwide, royalty-free, non-exclusive license with the exact terms of this License to Use, the Open Game Content. **5. Representation of Authority to Contribute**: If You are contributing original material as Open Game Content, You represent that Your Contributions are Your original creation and/or You have sufficient rights to grant the rights conveyed by this License. **6. Notice of License Copyright**: You must update the COPYRIGHT NOTICE portion of this License to include the exact text of the COPYRIGHT NOTICE of any Open Game Content You are copying, modifying or distributing, and You must add the title, the copyright date, and the copyright holder's name to the COPYRIGHT NOTICE of any original Open Game Content you Distribute. **7. Use of Product Identity**: You agree not to Use any Product Identity, including as an indication as to compatibility, except as expressly licensed in another, independent Agreement with the owner of each element of that Product Identity. You agree not to indicate compatibility or co-adaptability with any Trademark or Registered Trademark in conjunction with a work containing Open Game Content except as expressly licensed in another, independent Agreement with the owner of such Trademark or Registered Trademark. The use of any Product Identity in Open Game Content does not constitute a challenge to the ownership of that Product Identity. The owner of any Product Identity used in Open Game Content shall retain all rights, title and interest in and to that Product Identity. **8. Identification**: If you distribute Open Game Content You must clearly indicate which portions of the work that you are distributing are Open Game Content. **9. Updating the License**: Wizards or its designated Agents may publish updated versions of this License. You may use any authorized version of this License to copy, modify and distribute any Open Game Content originally distributed under any version of this License. **10. Copy of this License**: You MUST include a copy of this License with every copy of the Open Game Content You Distribute. **11. Use of Contributor Credits**: You may not market or advertise the Open Game Content using the name of any Contributor unless You have written permission from the Contributor to do so. **12. Inability to Comply**: If it is impossible for You to comply with any of the terms of this License with respect to some or all of the Open Game Content due to statute, judicial order, or governmental regulation then You may not Use any Open Game Material so affected. **13. Termination**: This License will terminate automatically if You fail to comply with all terms herein and fail to cure such breach within 30 days of becoming aware of the breach. All sublicenses shall survive the termination of this License. **14. Reformation**: If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable. **15. COPYRIGHT NOTICE**  \n **Open Game License v 1.0** Copyright 2000, Wizards of the Coast, Inc.  \n **System Reference Document**. Copyright 2000. Wizards of the Coast, Inc; Authors: Jonathan Tweet, Monte Cook, Skip Williams, based on material by E. Gary Gygax and Dave Arneson.  \n **The Archives of Nethys**. Copyright 2010, Blake Davis. **Pathfinder Open Reference**. \u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones.",
    "type": "section"
  },
  "links": [
    {
      "alt": "goblins",
      "aonid": 4,
      "game-obj": "Ancestries",
      "name": "goblins",
      "type": "link"
    },
    {
      "alt": "hobgoblins",
      "aonid": 13,
      "game-obj": "Ancestries",
      "name": "hobgoblins",
      "type": "link"
    },
    {
      "alt": "bugbears",
      "aonid": 17,
      "game-obj": "MonsterFamilies",
      "name": "bugbears",
      "type": "link"
    },
    {
      "alt": "darkvision",
      "aonid": 415,
      "game-obj": "Rules",
      "name": "darkvision",
      "type": "link"
    }
  ],
  "name": "Goblin",
  "schema_version": 1.1,
  "sources": [
    {
      "errata": {
        "alt": "4.0",
        "aonid": 1,
        "game-obj": "Sources",
        "name": "4.0",
        "type": "link"
      },
      "link": {
        "alt": "Core Rulebook pg. 632",
        "aonid": 1,
        "game-obj": "Sources",
        "name": "Core Rulebook pg. 632",
        "type": "link"
      },
      "name": "Core Rulebook",
      "page": 632,
      "type": "source"
    }
  ],
  "text": "A creature with this trait can be one of several kinds of creature, including goblins, hobgoblins, and bugbears. Goblins tend to have darkvision. An ability with this trait can be used or chosen only by goblins. A weapon with this trait is created and used by goblins.",
  "type": "trait"
}

=== devonjones/PFSRD2-Data/traits/gm_core/ingested.json
{
  "alternate_link": {
    "alternate_type": "legacy",
    "aonid": 95,
    "game-obj": "Traits",
    "type": "alternate_link"
  },
  "aonid": 633,
  "edition": "remastered",
  "game-id": "c80e26f9fa0dbec243b4a76aca7278df",
  "game-obj": "Traits",
  "license": {
    "license": "Open RPG Creative license",
    "name": "ORC Notice",
    "sections": [
      {
        "name": "Attribution",
        "sections": [
          {
            "name": "GM Core",
            "text": "***Pathfinder GM Core*** \u00a9 2023 Paizo Inc., Designed by Logan Bonner and Mark Seifter. Authors: Amirali Attar Olyaee, Logan Bonner, Creighton Broadhurst, Jason Bulmahn, James Case, Jesse Decker, Eleanor Ferron, Fabby Garza Marroqu\u00edn, Jaym Gates, Matthew Goetz, James Jacobs, Brian R. James, Jenny Jarzabski, Dustin Knight, Jason LeMaitre, Lyz Liddell, Luis Loza, Ron Lundeen, Stephen Radney-MacFarland, David N. Ross, Michael Sayre, Mark Seifter, Owen K.C. Stephens, Amber Stewart, Clark Valentine, Landon Winkler, and Linda Zayas-Palmer",
            "type": "section"
          }
        ],
        "text": "This product is based on the following Licensed Material:",
        "type": "section"
      },
      {
        "name": "Attributing us",
        "sections": [
          {
            "name": "Pathfinder Open Reference",
            "text": "\u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones.",
            "type": "section"
          }
        ],
        "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
        "type": "section"
      },
      {
        "name": "Reserved Material",
        "text": "Reserved Material elements in this product include, but may not be limited to: [none]",
        "type": "section"
      },
      {
        "name": "Expressly Designated Licensed Material",
        "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None].",
        "type": "section"
      }
    ],
    "subtype": "license",
    "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein.",
    "type": "section"
  },
  "name": "Ingested",
  "schema_version": 1.1,
  "sources": [
    {
      "errata": {
        "alt": "2.0",
        "aonid": 218,
        "game-obj": "Sources",
        "name": "2.0",
        "type": "link"
      },
      "link": {
        "alt": "GM Core pg. 248",
        "aonid": 218,
        "game-obj": "Sources",
        "name": "GM Core pg. 248",
        "type": "link"
      },
      "name": "GM Core",
      "page": 248,
      "type": "source"
    }
  ],
  "text": "An ingested poison is activated by applying it to food or drink to be consumed by a living creature, or by placing it directly into a living creature\u2019s mouth. A creature attempts a saving throw against such a poison when it consumes the poison or the food or drink treated with the poison. The onset time of ingested poisons typically ranges anywhere from 1 minute to 1 day",
  "type": "trait"
}

=== devonjones/PFSRD2-Data/traits/core_rulebook/move.json
{
    "name": "Move",
    "type": "trait",
    "alternate_link": {
        "type": "alternate_link",
        "game-obj": "Traits",
        "aonid": 658,
        "alternate_type": "remastered"
    },
    "edition": "legacy",
    "sources": [
        {
            "type": "source",
            "name": "Core Rulebook",
            "link": {
                "type": "link",
                "name": "Core Rulebook pg. 634",
                "alt": "Core Rulebook pg. 634",
                "game-obj": "Sources",
                "aonid": 1
            },
            "page": 634,
            "errata": {
                "type": "link",
                "name": "4.0",
                "alt": "4.0",
                "game-obj": "Sources",
                "aonid": 1
            }
        }
    ],
    "aonid": 114,
    "game-obj": "Traits",
    "game-id": "2b7846a8f10c24821bd06ec04adeb475",
    "text": "An action with this trait involves moving from one space to another.",
    "license": {
        "name": "OPEN GAME LICENSE Version 1.0a",
        "type": "section",
        "text": "The following text is the property of Wizards of the Coast, Inc. and is Copyright 2000 Wizards of the Coast, Inc (\"Wizards\"). All Rights Reserved.\n\n **1. Definitions**: (a)\"Contributors\" means the copyright and/or trademark owners who have contributed Open Game Content; (b)\"Derivative Material\" means copyrighted material including derivative works and translations (including into other computer languages), potation, modification, correction, addition, extension, upgrade, improvement, compilation, abridgment or other form in which an existing work may be recast, transformed or adapted; (c) \"Distribute\" means to reproduce, license, rent, lease, sell, broadcast, publicly display, transmit or otherwise distribute; (d)\"Open Game Content\" means the game mechanic and includes the methods, procedures, processes and routines to the extent such content does not embody the Product Identity and is an enhancement over the prior art and any additional content clearly identified as Open Game Content by the Contributor, and means any work covered by this License, including translations and derivative works under copyright law, but specifically excludes Product Identity. (e) \"Product Identity\" means product and product line names, logos and identifying marks including trade dress; artifacts; creatures characters; stories, storylines, plots, thematic elements, dialogue, incidents, language, artwork, symbols, designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual or audio representations; names and descriptions of characters, spells, enchantments, personalities, teams, personas, likenesses and special abilities; places, locations, environments, creatures, equipment, magical or supernatural abilities or effects, logos, symbols, or graphic designs; and any other trademark or registered trademark clearly identified as Product identity by the owner of the Product Identity, and which specifically excludes the Open Game Content; (f) \"Trademark\" means the logos, names, mark, sign, motto, designs that are used by a Contributor to identify itself or its products or the associated products contributed to the Open Game License by the Contributor (g) \"Use\", \"Used\" or \"Using\" means to use, Distribute, copy, edit, format, modify, translate and otherwise create Derivative Material of Open Game Content. (h) \"You\" or \"Your\" means the licensee in terms of this agreement.\n\n **2. The License**: This License applies to any Open Game Content that contains a notice indicating that the Open Game Content may only be Used under and in terms of this License. You must affix such a notice to any Open Game Content that you Use. No terms may be added to or subtracted from this License except as described by the License itself. No other terms or conditions may be applied to any Open Game Content distributed using this License.\n\n **3. Offer and Acceptance**: By Using the Open Game Content You indicate Your acceptance of the terms of this License.\n\n **4. Grant and Consideration**: In consideration for agreeing to use this License, the Contributors grant You a perpetual, worldwide, royalty-free, non-exclusive license with the exact terms of this License to Use, the Open Game Content.\n\n **5. Representation of Authority to Contribute**: If You are contributing original material as Open Game Content, You represent that Your Contributions are Your original creation and/or You have sufficient rights to grant the rights conveyed by this License.\n\n **6. Notice of License Copyright**: You must update the COPYRIGHT NOTICE portion of this License to include the exact text of the COPYRIGHT NOTICE of any Open Game Content You are copying, modifying or distributing, and You must add the title, the copyright date, and the copyright holder's name to the COPYRIGHT NOTICE of any original Open Game Content you Distribute.\n\n **7. Use of Product Identity**: You agree not to Use any Product Identity, including as an indication as to compatibility, except as expressly licensed in another, independent Agreement with the owner of each element of that Product Identity. You agree not to indicate compatibility or co-adaptability with any Trademark or Registered Trademark in conjunction with a work containing Open Game Content except as expressly licensed in another, independent Agreement with the owner of such Trademark or Registered Trademark. The use of any Product Identity in Open Game Content does not constitute a challenge to the ownership of that Product Identity. The owner of any Product Identity used in Open Game Content shall retain all rights, title and interest in and to that Product Identity.\n\n **8. Identification**: If you distribute Open Game Content You must clearly indicate which portions of the work that you are distributing are Open Game Content.\n\n **9. Updating the License**: Wizards or its designated Agents may publish updated versions of this License. You may use any authorized version of this License to copy, modify and distribute any Open Game Content originally distributed under any version of this License.\n\n **10. Copy of this License**: You MUST include a copy of this License with every copy of the Open Game Content You Distribute.\n\n **11. Use of Contributor Credits**: You may not market or advertise the Open Game Content using the name of any Contributor unless You have written permission from the Contributor to do so.\n\n **12. Inability to Comply**: If it is impossible for You to comply with any of the terms of this License with respect to some or all of the Open Game Content due to statute, judicial order, or governmental regulation then You may not Use any Open Game Material so affected.\n\n **13. Termination**: This License will terminate automatically if You fail to comply with all terms herein and fail to cure such breach within 30 days of becoming aware of the breach. All sublicenses shall survive the termination of this License.\n\n **14. Reformation**: If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable.\n\n **15. COPYRIGHT NOTICE**  \n **Open Game License v 1.0** Copyright 2000, Wizards of the Coast, Inc.  \n **System Reference Document**. Copyright 2000. Wizards of the Coast, Inc; Authors: Jonathan Tweet, Monte Cook, Skip Williams, based on material by E. Gary Gygax and Dave Arneson.  \n **The Archives of Nethys**. Copyright 2010, Blake Davis. **Pathfinder Open Reference**. \u00a9 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones.",
        "sections": [
            {
                "name": "Core Rulebook",
                "type": "section",
                "text": "**Pathfinder Core Rulebook (Second Edition)** \u00a9 2019, Paizo Inc.; Designers: Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter."
            }
        ],
        "subtype": "license",
        "license": "OPEN GAME LICENSE Version 1.0a"
    },
    "schema_version": 1.1
}
